name = "siteproauto-nextjs"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2026-04-17"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "ai-studio-applet-opennext-cache"
preview_bucket_name = "ai-studio-applet-opennext-cache"
